version: "3.8"
networks:
  monitoring:
    driver: bridge
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    container_name: my-app
    networks:
      - monitoring

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      networks:
        - monitoring
      ports:
        - "9090:9090"
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      depends_on:
        - cadvisor

  cadvisor:
      image: gcr.io/cadvisor/cadvisor:latest
      container_name: cadvisor
      ports:
        - "8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      networks:
        - monitoring
      depends_on:
        - redis

  redis:
      image: redis:latest
      container_name: redis
      networks:
        - monitoring
      ports:
        - "6379:6379"
